image: Visual Studio 2015

before_build:
- mkdir ..\build\ && cd ..\build\
- cmake -DCMAKE_BUILD_TYPE=Release ..\portaudio

build:
  project: ..\build\portaudio.sln
  parallel: true
  #verbosity: quiet

after_build:
- cd ..\portaudio
- 7z a pa19-win32-x86-release-build.7z ..\build\ .\include\

artifacts:
- path: .\pa19-win32-x86-release-build.7z
